name: Update README

on:
  push:
    branches:
    - main
    paths:
     - 'data/**'
     - '.github/workflows/updater.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Generate
      run: |
        make generator
    - name: Set Git Options
      run: | 
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "Alessandro Marino"
    - name: Update README
      run: |
        git add README.md
        git add outputs.json
        git commit -m "Update README"
        git push
    
